### ISSUE TITLE
PolyLine3D is not really 3D

### ISSUE THREAD

**Issue by mm-manu** [Birdasaur/FXyzLib#11]
I found that the PolyLine3d is not a real 3D line. It disappears when viewed from certain angles.
Please fix as suggested here: http://netzwerg.ch/blog/2015/03/22/javafx-3d-line/

**Comment by Birdasaur** [comment]
The PolyLine3D object is fine the way it is because it is not a collection of rotated cylinders like the link proposes but one contiguous TriangleMesh. The algorithm uses a pancake winding approach connecting the user points such that the faces on the back side are "flipped" and thus visible. The weakness is as you noted at certain camera angles the line becomes wafer thin. 
The solution your link proposes is inferior because it requires a new cylinder node be added to the scene for every line segment. This does not scale up beyond toy problems and quickly crushes the JavaFX rendering loop due to the number of nodes in the scene graph and the number of vertices to render. Cylinders have a lot of vertices.  
The PolyLine3D object is intended for maximum performance for large point lists like spacecraft orbits and ephemeris data which is why I wrote it.

**Comment by Birdasaur** [comment]
The PolyLine3D winding algorithm could be altered to have a non zero z dimension. However this would require a lot of trig similar to how the torus calculates its inner space. Additionally it would require some 3D shape... Triangle or greater... To perform the math around. This would fundamentally alter the usage from the original intent. A non trivial amount of work. 
But doable. Need to think about it a little.

**Comment by jperedadnr** [comment]
Note that if you just want a Line3D, you can use a FrustumMesh. There's a constructor where you can set the major and minor radius (use the same value for both), the height (not required), a level index (0 for the lower number of nodes), and initial and end 3D points:

 `FrustumMesh line3D = new FrustumMesh(0.1,0.1,1,0,new Point3D(-5,5,0),new Point3D(0,0,5));`

If you want to add several lines, you will face the problem of how they intersect at shared ends: we would need to implement some mechanism to add end caps. 

To overcome the problem of high number of nodes you can use the same approach we have used in ScatterMesh: use MeshHelper to create just one single mesh based on the meshes from each Line3D.

Finally, you can also use BezierMesh to create a true 3D polyline that interpolate several points using Bezier curves.

**Comment by macodar** [comment]
alright, thanks for the replies!

**Comment by Birdasaur** [comment]
That's a good idea Jose to use BezierMesh, though if the point list is too sparse it mind produce overly rounded lines.  He would have to mess with the control points to get it right but it would look nice and smooth.
The PolyLine3D avoids the end cap problem because it just winds the faces from point to point but that can cause jagged turns in the lines if the point list is sparse and the points have sharp angle differences.
